// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function fromElement(element) {
  if (element.tagName.toLowerCase() === "canvas") {
    return Caml_option.some(element);
  }
  
}

var Canvas = {
  fromElement: fromElement
};

export {
  Canvas ,
}
/* No side effect */
